issue 68 - display json, csv option for export; export json file functionality
dreamos82/chrome_parameters pull request #69
Opened 2019-10-30 15:14 UTC by Sonam3107

I can change the CSS for positioning and display. Please let me know.

2019-10-30 15:25 UTC, inuyasha82 commented
I'll review it soon, btw it will be merged after PR #67

2019-10-30 19:02 UTC, inuyasha82 requested changes

2019-10-30 19:02 UTC, inuyasha82 commented on src/popup.js
> +			new_element = document.createElement('div'),
I think this can be optimized and done into a function that iterate through the exporters array, get the keys, and create a div and then a relevant textnode using toUpperCase, add the event listener, etc. (even if we will not ave many other expoters, it makes the code little bit cleaner).

and with that function we will need only to do something like: 

new_element.appendChild(generate_html_block(exporterkey, exportervalue)); 

or it need just the key (the value can be extracted from the global variable exporters).
(this is just an example btw you can have it in your own way)

2019-10-30 19:02 UTC, inuyasha82 commented on src/popup.js
> +function create_json(parameters_array) {
This is already implemented in PR #67 so there is no need for that (the pull request was open 5 days ago, and i was already reviewing it so i prefer to finish and merge it, even to give credit to the author). (I tend to serve the PRs in a FCFS basis)

2019-10-31 05:33 UTC, Sonam3107 commented on src/popup.js
> +			new_element = document.createElement('div'),
Yes, that would be better. Will make the changes.

2019-10-31 05:33 UTC, Sonam3107 commented on src/popup.js
> +function create_json(parameters_array) {
It's alright. I understand. Just didn't knew about the PR.

2019-10-31 05:49 UTC, Sonam3107 commented on src/popup.js
> +function create_json(parameters_array) {
I have made the suggested changes.

2019-10-31 05:50 UTC, Sonam3107 commented
I have made the suggested changes.

2019-10-31 09:37 UTC, inuyasha82 commented
I merged with master

2019-10-31 19:24 UTC, inuyasha82 commented
I checked the layout, i think that we can improve it, let me know if you want to do it, otherwise i can do it by myself, the options are maybe too small, and I'm wondering could be better to have them on the same line, maybe just well spaced? And another thing maybe we should align them with. the other buttons? 
(these are mostly ideas, I'm open to any suggestion, improvement but I think at least have them bigger and aligned will improve the look and feel )

2019-11-06 10:04 UTC, inuyasha82 commented
Hey @Sonam3107 do you want to implement those changes, or if u don't have time, i can have a look at them.

2019-11-06 19:41 UTC, inuyasha82 commented
Ok i'm going to merge it, i already made the changes and i'll merge them just after this PR. 
Thank you again!

2019-11-06 19:41 UTC, merged

2019-11-07 20:08 UTC, Sonam3107 commented
Hey @inuyasha82 , sorry that I couldn't take up the changes.

2019-11-07 20:14 UTC, inuyasha82 commented
No problem was a very tiny change (5 or six lines of code! :) )